[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "x-mcp"
version = "0.2.0"
description = "Twitter search tool for FastMCP using Twikit"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
    { name = "lord-dubious", email = "chukwurahdavid@gmail.com" }
]
dependencies = [
    "fastmcp",
    "twikit",
    "requests",
]

[project.urls]
Homepage = "https://github.com/lord-dubious/mcp-twikit"

[project.scripts]
x-mcp = "mcp_twikit.twitter:mcp.run"
